<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>AabSemantics</PackageId>
    <Version>2.3.0</Version>
    <Description>This project represents semantic network engine written in C#. Please, see more details in project Wiki.</Description>
    <PackageTags>AI;semantic network</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>IRepository and Entity Framework extensions have been made cancellable.</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Modules\Classification\Attributes\" />
    <Folder Include="Modules\Classification\Concepts\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
