<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AabSemantics.Extensions.EF</RootNamespace>
    <AssemblyName>AabSemantics.Extensions.EF</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\AabSemantics\AabSemantics.csproj" />
  </ItemGroup>

</Project>
