<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AabSemantics.Extensions.EF</RootNamespace>
    <AssemblyName>AabSemantics.Extensions.EF</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <Description>AabSemantics.Extensions.EF</Description>
    <Company>Andrei Bychko</Company>
    <Product>AabSemantics</Product>
    <Copyright>Copyright © Andrei Bychko 2014-2026</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\AabSemantics\AabSemantics.csproj" />
  </ItemGroup>

</Project>
